### ISSUE TITLE
2022.05.09.(월) 프로젝트 전체 피드백(To-do list)

### ISSUE THREAD

**Issue by heejaykong** [SukheeChoi/springframework-mini-project#191]
#### 2022.05.09.(월) 프로젝트 전체 피드백

메인화면:
- [ ] 메인화면에 포인트로 스케일링 혜택 있다는 inform하기
- [ ] 메인화면 신경을 많이 써라

로그인:
- [ ] 로그인 후 리다이렉트는 마이페이지로. (@heejaykong )

치과 상세화면:
- [ ] 치과 이미지 띄우기(각각 치과서버에서 url갖고오기) (@SukheeChoi )
- [ ] 치과상세화면 리뷰에 프로필 사진 넣어라 (@lee0507 )
- [ ] 치과 디테일화면에 아니 근데 왜 시안대로 안돼있는게 많어 우리ㅋㅋㅋㅋ 전화번호 누르면 전화되게끔 해라 (@zzeongm )

treatment화면:
- [ ] details화면 내용 리스트로 죄다 보여주지말고 펼쳐졌다접혔다 하는 걸로 해보라고...

reservation화면:
- [ ] 진료예약하기 화면에도 치과 이미지 넣어라(내치과면 표시하는거 어떤지)
- [ ] 시간선택이 미리 나오도록 해라 (@zzeongm )
- [ ] 예약취소할때 정말 취소하겠습니까 모달 띄우기 (@heejaykong )

캘린더:
- [ ] 스케줄 상세다이얼로그를 바꾸든 밑에서 올라오든 암튼 디자인을 바꿔라 (@zzeongm )

공통:
- [ ] 페이지네이션도 모바일에 맞춰서 해라(무한스크롤 구현해보든가)

> 한줄평: 잘했네. 화요일부터 피피티 작업 들어가라

끝.
